!!omap
- OUTPUT_DIR: inference_DepressionAnalysis
- SAVE_CONFIG_NAME: config_inference_DepressionAnalysis.yaml
- CKPTS_DIR: /cvhci/temp/wpingcheng/ckpts_new/
- TYPE: V+Conv2D-BiLSTM+PHQ-Subscores
- MANUAL_SEED: 1
- LOG_TITLE: Depression Detection with visual features (key points & gaze direction),
    Conv2D-BiLSTM, PHQ-Subscores
- DATA: !!omap
  - TRAIN_ROOT_DIR: /cvhci/temp/wpingcheng/DAIC_WOZ-generated_database_V2/train/clipped_data/
  - VALIDATION_ROOT_DIR: /cvhci/temp/wpingcheng/DAIC_WOZ-generated_database_V2/train/original_data/
  - TEST_ROOT_DIR: /cvhci/temp/wpingcheng/DAIC_WOZ-generated_database_V2/test/clipped_data/
  - USE_MEL_SPECTROGRAM: false
  - VISUAL_WITH_GAZE: true
  - PADDING:
  - RESCALE_SIZE:
  - CROP_SIZE:
  - BATCH_SIZE: 500
  - NUM_WORKERS: 0
- MODEL: !!omap
  - PHQ_THRESHOLD: 10
  - EPOCHS: 1
  - WEIGHTS: !!omap
    - TYPE: other
    - DATE:
    - PATH: model_weights
    - NAME: V+Conv2D-BiLSTM+PHQ-Subscores+Soft_2022-03-15_170617_f1_score-0.6094.pt
    - CUSTOM_ABSOLUTE_PATH:
    - INCLUDED:
      - visual_net
      - evaluator
  - VISUAL_NET: !!omap
    - INPUT_DIM: 3
    - CONV_HIDDEN: 256
    - LSTM_HIDDEN: 256
    - OUTPUT_DIM: 256
    - NUM_LAYERS: 4
    - ACTIVATION: relu
    - NORM: bn
    - DROPOUT: 0.6
  - EVALUATOR: !!omap
    - PREDICT_TYPE: phq-subscores
    - INPUT_FEATURE_DIM: 256
    - CLASSES_RESOLUTION: 32
    - N_CLASSES: 4
    - N_SUBSCORES: 8
    - STD: 5
  - CRITERION: !!omap
    - USE_SOFT_LABEL: true
    - USE_WEIGHTS: true
  - OPTIMIZER: !!omap
    - LR: 0.0001
    - WEIGHT_DECAY: 1e-05
    - USE_SAM: true
  - SCHEDULER: !!omap
    - STEP_SIZE: 10
    - GAMMA: 0.9
